global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # ------------------------
  # FastAPI Metrics
  # ------------------------
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:8000

  # ------------------------
  # EC2 Host Metrics (Node Exporter)
  # ------------------------
  - job_name: "node-exporter"
    static_configs:
      - targets:
          - node-exporter:9100
