global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "ec2-host"
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          group: "Infrastructure"