global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:8000

  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "52.0.84.95/:9100"
