name: CI-CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  ci:
    name: CI - Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push FastAPI image
        uses: docker/build-push-action@v5
        with:
          context: ./Multi-Container-Docker/backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-backend:latest

  cd:
    name: CD - Deploy to EC2
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync Files and Restart Docker
        run: |
          # 1. Sync updated config files to the live folder
          # This ensures prometheus.yml and the json dashboards are moved
          rsync -avz --delete --exclude='.git' ./Multi-Container-Docker/ /home/ec2-user/OmerOps/Multi-Container-Docker/

          # 2. Navigate to the live folder
          cd /home/ec2-user/OmerOps/Multi-Container-Docker

          # 3. Pull new images and restart services
          docker compose pull
          docker compose up -d

          # 4. Cleanup: Remove dangling images and build cache to save EC2 space
          docker image prune -f